name: Lint Ansible Playbooks

on:
  push

jobs:
  lint-playbooks:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - uses: actions/checkout@v2
    - name: Run ansible-lint
      run: ansible-lint -v *.yaml
