name: Lint Ansible Playbooks

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  lint-playbooks:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - uses: actions/checkout@v2
    - name: Change to Ansible directory and clone Ansible Repo
      run: git clone https://github.com/rubrikinc/rubrik-modules-for-ansible.git
    - name: Stage Ansible files
      run: cd rubrik-modules-for-ansible/ && cp -R rubrikinc .. && cp ansible.cfg ..    
    - name: Run ansible-lint
      run: ansible-lint -v *.yaml
