name: Run Ansible Playbooks

on:
  push:
    branches:
      - master

jobs:
  run-playbooks:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Run a one-line script
      run: echo Hello, world!
